# Set to other image if needed
ARG BASE_IMAGE="quay.io/ascend/vllm-ascend:v0.11.0"

FROM ${BASE_IMAGE}

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG ENABLE_SPARSE=true

WORKDIR /workspace

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

RUN export PLATFORM="ascend" ENABLE_SPARSE=$ENABLE_SPARSE && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    pip install -v -e /workspace/unified-cache-management --no-build-isolation

# Apply patch for vLLM
RUN if [ "$ENABLE_SPARSE" = "true" ]; then \
    echo "Applying vLLM patch for sparse feature..." && \
    cd /vllm-workspace/vllm && \
    git apply /workspace/unified-cache-management/ucm/integration/vllm/patch/0.11.0/vllm-adapt.patch && \
    cd /vllm-workspace/vllm-ascend && \
    git apply /workspace/unified-cache-management/ucm/integration/vllm/patch/0.11.0/vllm-ascend-adapt.patch; \
else \
    echo "Skipping vLLM patch (ENABLE_SPARSE is not true)"; \
fi

CMD ["/bin/bash"]